# start yaml
version: '1.0.0'

services:
  db:
    container_name: ${PROJECT_NAME}-db-${CONTAINER_SUFFIX:-local}
    image: postgres:latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1m30s
      timeout: 30s
      retries: 3
    environment:
      TZ: UTC
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
  db-migrate:
    container_name: ${PROJECT_NAME}-db-migrate-${CONTAINER_SUFFIX:-local}
    image: migrate/migrate
    restart: "no"
    entrypoint: ""
    environment:
      TZ: UTC
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${PROJECT_NAME}?sslmode=disable
      # DB_URL: postgres://postgres:postgrespw@localhost:55001
volumes:
  migrations:
    name: ${PROJECT_NAME}-api-migrate-${CONTAINER_SUFFIX:-local}
