// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type School struct {
	ID    string `json:"ID"`
	Name  string `json:"Name"`
	Email string `json:"Email"`
}

type Student struct {
	ID    string `json:"ID"`
	Name  string `json:"Name"`
	Phone string `json:"Phone"`
	Email string `json:"Email"`
}

type Subject struct {
	ID   string `json:"ID"`
	Name string `json:"Name"`
}

type Teacher struct {
	ID    string `json:"ID"`
	Name  string `json:"Name"`
	Phone string `json:"Phone"`
	Email string `json:"Email"`
}

type NewSchool struct {
	Name  string `json:"Name"`
	Email string `json:"Email"`
}

type NewStudent struct {
	Name  string `json:"Name"`
	Phone string `json:"Phone"`
	Email string `json:"Email"`
}

type NewSubject struct {
	Name string `json:"Name"`
}

type NewTeacher struct {
	Name  string `json:"Name"`
	Phone string `json:"Phone"`
	Email string `json:"Email"`
}
